apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: kube
build:
  artifacts:
    - image: https://github.com/ashok-ravi/kube
      jib:
        project: com.ar:kube
deploy:
  helm:
    releases:
      - name: rest-service
        chartPath: rest-service
        valuesFiles:
          - rest-service/values.yaml
        version: 0.1.0
